- hosts: all
  become: true

#  vars:
#    redmine_port: 3000

  tasks:
    - name: cp env
      template:
        src: ./templates/.env.redmine.j2
        dest: .env
        mode: '0644'
      tags: deploy

    - name: up redmine
      community.docker.docker_container:
        name: redmine
        image: redmine
        restart_policy: unless-stopped
#        ports: [3000:3000]
        ports:
          - "{{ redmine_port }}:3000"
        env_file: .env
        state: started
#        restart_policy: always
      tags: deploy
