- hosts: all
  become: true

  tasks:
    - name: cp env
      template:
        src: ./templates/.env.redmine.j2
        dest: .env
        mode: '0644'
      tags: deploy

    - name: up redmine
      community.docker.docker_container:
        name: redmine
        image: redmine
        restart_policy: unless-stopped
        ports:
          - "{{ redmine_port }}:3000"
        env_file: .env
        state: started
      tags: deploy

- hosts: webservers
  become: true

  roles:
    - role: datadog.dd.agent
      tags: monitoring
