- name: Deploying redmine
  hosts: all
  become: true

  tasks:
    - name: cp env
      template:
        src: ./templates/.env.redmine.j2
        dest: .env
        mode: '0644'
      tags: deploy

    - name: up redmine
      community.docker.docker_container:
        name: redmine
        image: redmine
        restart_policy: unless-stopped
        ports:
          - "{{ redmine_port }}:3000"
        env_file: .env
        state: started
      tags: deploy

- name: Install Datadog monitoring
  hosts: webservers
  become: true
  vars:
    datadog_api_key: "{{ datadog_api_key }}"
    datadog_site: "datadoghq.eu"

#  roles:
#    - role: datadog.dd

  tasks:
    - name: Install DD
      import_role:
        name: datadog.dd

    - name: Copy configuration file
      ansible.builtin.template:
        src: ./templates/datadog.yaml.j2
        dest: /etc/datadog-agent/conf.d/http_check.d/conf.yaml
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: Restart agent
      ansible.builtin.service:
        name: datadog-agent
        state: restarted
